<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">

    <title>Todolist de tata Ursule</title>
    <link rel="icon" type="image/png" href="img/favicon.png" />

    <link href="https://fonts.googleapis.com/css?family=Lobster+Two|Roboto" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="css/style.css">
</head>

<body>

<header>
    <h1>La Todolist de tata Ursule</h1>
    <figure id="kiki" class="tooltiped">
        <img src="img/kiki.jpg" />
        <span class="tooltip">ouah&nbsp;! ouah&nbsp;!</span>
    </figure>
</header>

<main>

    <?php if ((file_exists("todolist.csv")) && (filesize("todolist.csv") > 0)): ?>

    <section id="todolist">
        <form id="deleteTasks" action="index.php" method="post">
            <div class="form-group checkbox-group">
                <?php displayList(); ?>
            </div>

            <div class="form-group submit">
                <input id="delete" name="delete" type="hidden" value="true" />
                <input id="resetDelete" type="reset" value="Annuler" />
                <input id="submitDelete" type="submit" value="Supprimer" disabled />
            </div>
        </form>
    </section>

    <?php endif; ?>

    <section id="formulaire">
        <h2>Nouvelle tâche</h2>
        <form id="addNewTask" action="index.php" method="post">
            <div class="form-group">
                <label class="h3" for="title">Titre<span id="title-help" class="alert">&nbsp;: doit comporter au moins trois caractères&nbsp;!</span></label>
                
                <input name="title" id="title" type="text" required />
            </div>

            <div class="form-group">
                <label class="h3" for="description">Description</label>
                <textarea name="description" id="description"></textarea>
            </div>

            <div class="form-group">
                <label class="h3" for="date">Date de fin</label>

                <select name="day" id="day">
                    <option value="01">01</option>
                    <option value="02">02</option>
                    <option value="03">03</option>
                    <option value="04">04</option>
                    <option value="05">05</option>
                    <option value="06">06</option>
                    <option value="07">07</option>
                    <option value="08">08</option>
                    <option value="09">09</option>
                    <option value="10">10</option>
                    <option value="11">11</option>
                    <option value="12">12</option>
                    <option value="13">13</option>
                    <option value="14">14</option>
                    <option value="15">15</option>
                    <option value="16">16</option>
                    <option value="17">17</option>
                    <option value="18">18</option>
                    <option value="19">19</option>
                    <option value="20">20</option>
                    <option value="21">21</option>
                    <option value="22">22</option>
                    <option value="23">23</option>
                    <option value="24">24</option>
                    <option value="25">25</option>
                    <option value="26">26</option>
                    <option value="27">27</option>
                    <option value="28">28</option>
                    <option value="29">29</option>
                    <option value="30">30</option>
                    <option value="31">31</option>
                </select>
                <select name="month" id="month">
                    <option value="01">Janvier</option>
                    <option value="02">Février</option>
                    <option value="03">Mars</option>
                    <option value="04">Avril</option>
                    <option value="05">Mai</option>
                    <option value="06">Juin</option>
                    <option value="07">Juillet</option>
                    <option value="08">Août</option>
                    <option value="09">Septembre</option>
                    <option value="10">Octobre</option>
                    <option value="11">Novembre</option>
                    <option value="12">Décembre</option>
                </select>
                <select name="year" id="year">
                    <option value="2017">2017</option>
                    <option value="2018">2018</option>
                    <option value="2019">2019</option>
                    <option value="2020">2020</option>
                    <option value="2021">2021</option>
                    <option value="2022">2022</option>
                    <option value="2023">2023</option>
                    <option value="2024">2024</option>
                    <option value="2025">2025</option>
                </select>
            </div>

            <h3 for="priority">Priorité</h3>
            <div class="form-group radio-group">
                <input type="radio" id="priority" name="priority" value="low" />
                <label for="lowpriority">Basse</label>
                <input type="radio" id="priority" name="priority" value="normal" checked />
                <label for="normalpriority">Normale</label>
                <input type="radio" id="priority" name="priority" value="high" />
                <label for="highpriority">Haute</label>
            </div>
            
            <div class="form-group submit">
                <input id="new" name="new" type="hidden" value="true" />
                <input id="resetNew" type="reset" value="Annuler" />
                <input id="submitNew" type="submit" value="Ajouter" disabled />
            </div>
        </form>
    </section>
</main>

<footer>
    <p><em>Exercice réalisé dans le cadre de la formation de Développeur/Intégrateur Web à la <a href="https://3wa.fr/">3W Academy</a>.</em></p>
</footer>

<script src="js/kiki.js"></script>
<script src="js/checkForm.js"></script>
<script src="js/modifyTask.js"></script>

</body>
</html>