<div id="task-<?php echo $taskArray[0]; ?>" class="tooltiped check-item <?php echo $taskArray[4]; ?>">
    <input type="checkbox" class="checkboxItem" name="task[]" value="<?php echo $taskArray[0]; ?>" />
    <label for="<?php echo $taskArray[0]; ?>"><?php echo $taskArray[2]; enRetard($taskArray[1]); ?></label>
    <span class="tooltip"><?php echo $taskArray[3]; ?> <em>(avant le <?php echo $taskArray[1]; ?>)</em></span>
</div>